### ISSUE TITLE
Infection works incorrectly on Windows

### ISSUE THREAD

**Issue by borNfreee** [infection/infection#351]
| Question    | Answer
| ------------| ---------------
| Infection version | `master`
| Test Framework version | PHPUnit
| PHP version | 7.2

 https://ci.appveyor.com/project/borNfreee/infection/build/job/3mf37ov3vjg6xakm

See 100% covered MSI. It definitely not a correct result.

**Comment by BackEndTea** [comment]
After a bit of debugging i found that the phpunit executable is a bit different on windows:
```sh
#!/usr/bin/env sh

dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../phpunit/phpunit" && pwd)

if [ -d /proc/cygdrive ] && [[ $(which php) == $(readlink -n /proc/cygdrive)/* ]]; then
   # We are in Cgywin using Windows php, so the path must be translated
   dir=$(cygpath -m "$dir");
fi

"${dir}/phpunit" "$@"
```

Meaning it can't be executed as a php process, but #343 *should* fix this issue.

**Comment by sanmai** [comment]
We really need *some* E2E tests running under Windows, if not all.

**Comment by sanmai** [comment]
So I've added an E2E test with phpunit.bat in #343, so far so good. How can we check that this issue is actually got fixed by that PR?

**Comment by borNfreee** [comment]
we can merge #343 and rebase this one on master

**Comment by borNfreee** [comment]
seems like #343 didn't fix the issue https://ci.appveyor.com/project/borNfreee/infection/build/job/0scwrx7xu7epcw8v

**Comment by BackEndTea** [comment]
https://github.com/infection/infection/blob/26c457a53737f010fc3a5759cb4df99df534f4c9/src/Finder/TestFrameworkFinder.php#L99-L103

We can make the `.bat` part the first option here, which worked on my system. However this does indicate there might be something else going on

https://github.com/infection/infection/blob/26c457a53737f010fc3a5759cb4df99df534f4c9/src/TestFramework/AbstractTestFrameworkAdapter.php#L145

I think that `is_executable` may behave a bit different on windows, since i had issues with it on the windows tests as well for the test that infection is executable. 

Running `command -v php` in the windows commandline also gives an error, so it might be that.

**Comment by BackEndTea** [comment]
We should not rely on `is_executable`:
https://bugs.php.net/bug.php?id=41062

**Comment by sanmai** [comment]
Reading that bug report it seems we should be fine with `is_executable` because PHPUnit uses `.bat` which is always an executable under Windows.

**Comment by BackEndTea** [comment]
> Reading that bug report it seems we should be fine with is_executable because PHPUnit uses .bat which is always an executable under Windows.

When it picks up the bat file it is indeed not an issue, however since that option is the last check, it will instead find the default executable first, which is not executable according to windows logic.

https://github.com/infection/infection/blob/26c457a53737f010fc3a5759cb4df99df534f4c9/src/Finder/TestFrameworkFinder.php#L99-L103

**Comment by sanmai** [comment]
Oh, do you mean that if we'd be looking for `.bat` first on Windows, that'll solve the issue?
